/** The code below was generated by mostly by Gemini**/
"use client"; // Directs Next.js to render this on the client side (the browser) to allow for user interaction and state.

import { useRef, useState } from "react"; // Hook to manage data that changes over time (like user input and AI responses).

export default function Home() {
  /**
   * STATE MANAGEMENT:
   * 'input' stores what the user types in the text box.
   * 'reply' stores the final response string received from the FastAPI backend.
   * 'loading' is a boolean flag to track if a request is currently in flight (used to show "Sending..." on the button).
   */
  // Define what a "Message" looks like for TypeScript
  type Message = { role: "user" | "assistant", content: string };

  // This array will hold the running conversation
  const [chatHistory, setChatHistory] = useState<Message[]>([]);
  const chatHistoryRef = useRef<Message[]>([]);
  const [input, setInput] = useState("");
  const [reply, setReply] = useState("");
  const [loading, setLoading] = useState(false);
  const [recording, setRecording] = useState(false);
  const [mediaRecorder, setMediaRecorder] = useState<MediaRecorder | null>(null);

  //NEW STATE : Default to Beginner
  const [difficulty, setDifficulty] = useState("Beginner");

  //NEW STATE: speed of speech
  const [audioSpeed, setAudioSpeed] = useState<number>(0.5);

  const silenceTimer = useRef<NodeJS.Timeout | null>(null);
  const idleTimer = useRef<NodeJS.Timeout | null>(null); // Add this new tracker!
  const audioContext = useRef<AudioContext | null>(null);
  let currentAudio: HTMLAudioElement | null = null;

    /**
   * ASYNCHRONOUS COMMUNICATION FUNCTION:
   * This handles the "Handshake" with your Python server. 
   * It is 'async' because we don't want the UI to freeze while waiting for a response over the network.
   */
  const sendMessage = async (textOverride?: string) => {
    const messageToSend = textOverride || input;
    if (!messageToSend || messageToSend.trim().length < 2) return;
    // Step 1: Start loading state to disable the button and give user feedback
    setLoading(true);

    // 1. Instantly update the UI and history with what the user just said
    const newUserMessage: Message = { role: "user", content: messageToSend };
    
    // LIGHTWEIGHT MEMORY TRICK: We use .slice(-10) to only keep the last 10 messages (5 interactions).
    // This prevents the context window from getting too large and eating all your API credits!
    const updatedHistory = [...chatHistoryRef.current, newUserMessage].slice(-10); 

    chatHistoryRef.current = updatedHistory;
    setChatHistory(updatedHistory);

    try {
      /**
       * FETCH API CALL:
       * We send a POST request to our local FastAPI server.
       * - method: "POST" because we are sending data, not just requesting it.
       * - headers: Informs the server that the body contains JSON data.
       * - body: Converts the JavaScript object { message: input } into a JSON string.
       */
      const response = await fetch("http://localhost:8000/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({message: updatedHistory, difficulty: difficulty}),
      });

      // Step 2: Extract the JSON body from the server's response
      const data = await response.json();

      // 3. Add the bot's reply to the history array
      const newBotMessage: Message = { role: "assistant", content: data.reply };

      // Update both again with the bot's reply!
      chatHistoryRef.current = [...chatHistoryRef.current, newBotMessage];
      setChatHistory([...chatHistoryRef.current]);
      
      /**
       * Step 3: Update the 'reply' state with the message from the backend.
       * Based on our main_backend.py, the backend returns: {"reply": "...", "difficulty": "..."}
       */
      setReply(data.reply);

      
      // Trigger ElevenLabs to speak the response!
      if (data.reply) {
        await playAudioResponse(data.reply);
      }
        
    } catch (error) {
      // Error Handling: If the backend is offline or the network fails, log the error and notify the user.
      console.error("Error communicating with backend:", error);
      setReply("Error: Could not reach the server. Make sure your FastAPI backend is running.");
    } finally {
      // Step 4: Turn off loading state regardless of whether the request succeeded or failed.
      setLoading(false);
    }
  };

  const startRecording = async() => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({audio : true});
      const recorder = new MediaRecorder(stream);
      let chunks: BlobPart[] = [];

      recorder.ondataavailable = (e) => chunks.push(e.data)
      recorder.onstop = async() => {
        const audioBlob = new Blob(chunks, {type: 'audio/webm'});
        sendAudioToBackend(audioBlob);
      
      }
    
      setMediaRecorder(recorder);
      setRecording(true);
      recorder.start();

      // 2. THE SILENCE DETECTOR
      // ==========================================
      audioContext.current = new AudioContext();
      const source = audioContext.current.createMediaStreamSource(stream);
      const analyzer = audioContext.current.createAnalyser();
      analyzer.fftSize = 512;
      source.connect(analyzer);

      const bufferLength = analyzer.frequencyBinCount;
      const dataArray = new Uint8Array(bufferLength);

        let hasSpoken = false; // Track if they ever made a sound

      const checkSilence = () => {
        if (recorder.state !== "recording") return;

        analyzer.getByteFrequencyData(dataArray);
        const currentVolume = dataArray.reduce((a, b) => a + b, 0) / bufferLength;

        if (currentVolume > 30) {
          // User is making noise! Mark that they have spoken.
          hasSpoken = true;

          // Clear BOTH timers because they are actively talking
          if (silenceTimer.current) {
            clearTimeout(silenceTimer.current);
            silenceTimer.current = null;
          }
          if (idleTimer.current) {
            clearTimeout(idleTimer.current);
            idleTimer.current = null;
          }
        } else {
          // It is silent. Which timer do we use?
          if (hasSpoken) {
            // They spoke previously, but paused. Wait 3 seconds to send message.
            if (!silenceTimer.current) {
              silenceTimer.current = setTimeout(() => {
                console.log("3 seconds of pause detected. Sending to bot!");
                recorder.stop(); // Triggers onstop -> sendAudioToBackend
              }, 3000); 
            }
          } else {
            // They haven't said a single word yet. Wait 10 seconds to shut down.
            if (!idleTimer.current) {
              idleTimer.current = setTimeout(() => {
                console.log("10 seconds of absolute silence. Shutting down.");
                
                // IMPORTANT: We delete the onstop function so it doesn't 
                // accidentally send 10 seconds of empty silence to OpenAI!
                recorder.onstop = null; 
                
                // Safely close the microphone loop
                stopRecording(); 

              }, 10000); // 10000 milliseconds = 10 seconds
            }
          }
        }

        // Loop this function to keep checking
        requestAnimationFrame(checkSilence);
      };
  
      checkSilence();

    } catch (error) {
        console.error("Error accessing microphone:", error);
    }
  };
  const sendAudioToBackend = async (blob : Blob) => {
    if (blob.size < 100) {
      console.warn("Audio file is too small or empty.");
      return;
    }

    setLoading(true);
    try {
      // Create a form container to hold the audio file
      const formData = new FormData();
      // name the field "file" to match what fastAPI expects
      formData.append("file", blob, "recording.webm")
      
      // 2. Send it to the new speech to text endpoint in the backend
      const response = await fetch("http://localhost:8000/speech-to-text", {
      method: "POST",
      body: formData,});

     // 1. Check if the server crashed (500) or couldn't be found (404)
      if (!response.ok) {
        console.error("Server Error:", response.status);
        return; 
      }

      const data = await response.json() as { text?: string; error?: string};

      // 2. Safely parse the response
      console.log("Backend sent this exact data:", data); // Look in your browser console for this!

      // 3. The "Null" Guard
      if (!data) {
        console.error("The backend sent an empty/null response.");
        return;
      }

      // 4. Check for explicit errors from our Python backend
      if (data.error) {
        console.error("Whisper failed:", data.error);
        // Optional: alert(`Audio error: ${data.error}`);
        return;
      }

      // 5. Finally, if we safely made it here, set the text!
      if (data.text) {
        setInput(data.text);

        await sendMessage(data.text);
      } else {
        console.warn("No text was found in the response.");
      }
    }
      // 3. Take what text Whisper found and use it as the input
      catch (error) {
        console.error("Speech-to-text failed: ", error);
      }
      finally {
        setLoading(false)
      }
      
  };

  const stopRecording = () => {
    if (mediaRecorder) {
      mediaRecorder.onstop = null; 
      
      if (mediaRecorder.state === "recording") {
        mediaRecorder.stop();
      }
    }
    
    setRecording(false);

// 2. THE FIX: Kill the bot's voice and destroy the "auto-start" hook
    if (currentAudio) {
      currentAudio.pause();
      currentAudio.onended = null;
    }

    // Clear the silence timer
    if (silenceTimer.current) {
      clearTimeout(silenceTimer.current);
      silenceTimer.current = null;
    }

    if (idleTimer.current) { 
      clearTimeout(idleTimer.current);
      idleTimer.current = null;
    }

    // Turn off the volume analyzer
    if (audioContext.current) {
      audioContext.current.close();
      audioContext.current = null;
    }
  };
  const playAudioResponse = async (textToSpeak: string) => {
  try {
    const response = await fetch("http://localhost:8000/text-to-speech", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ text: textToSpeak, speed: audioSpeed}),
    });

    if (!response.ok) throw new Error("Failed to fetch audio");

    // Convert the incoming stream into a playable "Blob"
    const audioBlob = await response.blob();
    const audioUrl = URL.createObjectURL(audioBlob);
    
    // Create an HTML5 Audio object
    const audio = new Audio(audioUrl);
    
    if (currentAudio) {
      currentAudio.pause();
    }

    currentAudio = new Audio(audioUrl);
    
    currentAudio.onended = () => {
          console.log("Bot finished speaking. Turning microphone back on!");
          // Automatically trigger the microphone again!
          startRecording(); 
    };
    
    currentAudio.play();

  } catch (error) {
    console.error("Audio playback error:", error);
  }
  };

  return (
    // MAIN LAYOUT CONTAINER
  <main style={{ 
      minHeight: "100vh", 
      backgroundColor: "#f4f7f6", 
      display: "flex", 
      justifyContent: "center", 
      padding: "40px 20px",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
    }}>
      
      {/* APP CARD CONTAINER */}
      <div style={{ 
        backgroundColor: "#ffffff", 
        maxWidth: "600px", 
        width: "100%", 
        borderRadius: "16px", 
        boxShadow: "0 10px 25px rgba(0, 0, 0, 0.05)", 
        padding: "40px 30px",
        display: "flex",
        flexDirection: "column",
        gap: "24px" // This creates perfectly even spacing between all sections
      }}>
        
        {/* HEADER */}
        <div style={{ textAlign: "center" }}>
          <h1 style={{ margin: "0 0 8px 0", color: "#111827", fontSize: "2rem" }}>Spanish Travel Companion</h1>
          <p style={{ margin: "0", color: "#6b7280", fontSize: "1rem" }}>Habla conmigo para practicar.</p>
        </div>

        {/* PRIMARY ACTION: VOICE RECORDING */}
        <div style={{ display: "flex", justifyContent: "center", padding: "10px 0" }}>
          {!recording ? (
            <button 
              onClick={startRecording} 
              style={{ 
                padding: "16px 32px", backgroundColor: "#10b981", color: "white", 
                border: "none", borderRadius: "50px", fontSize: "1.1rem", 
                fontWeight: "bold", cursor: "pointer", boxShadow: "0 4px 10px rgba(16, 185, 129, 0.3)",
                display: "flex", alignItems: "center", gap: "8px", transition: "transform 0.2s"
              }}
            >
              🎙️ Start Speaking
            </button>
          ) : (
            <button 
              onClick={stopRecording} 
              style={{ 
                padding: "16px 32px", backgroundColor: "#ef4444", color: "white", 
                border: "none", borderRadius: "50px", fontSize: "1.1rem", 
                fontWeight: "bold", cursor: "pointer", boxShadow: "0 4px 10px rgba(239, 68, 68, 0.3)",
                display: "flex", alignItems: "center", gap: "8px"
              }}
            >
              ⏹ Stop Recording
            </button>
          )}
        </div>

        {/* BOT RESPONSE AREA */}
        {reply && (
          <div style={{ 
            backgroundColor: "#f0fdf4", 
            borderLeft: "4px solid #10b981", 
            padding: "20px", 
            borderRadius: "0 8px 8px 0"
          }}>
            <h2 style={{ fontSize: "0.85rem", color: "#10b981", textTransform: "uppercase", letterSpacing: "1px", margin: "0 0 8px 0" }}>Companion Reply</h2>
            <p style={{ fontSize: "1.2rem", fontWeight: "500", color: "#111827", margin: "0", lineHeight: "1.5" }}>{reply}</p>
          </div>
        )}

        {/* TEXT INPUT BACKUP */}
        <div style={{ display: "flex", gap: "10px" }}>
          <input 
            type="text" 
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Or type your message here..."
            style={{ 
              flex: 1, padding: "14px", borderRadius: "8px", 
              border: "1px solid #e5e7eb", fontSize: "1rem", outline: "none",
              backgroundColor: "#f9fafb", color: "#111827"
            }}
          />
          <button 
            onClick={() => sendMessage()}
            disabled={loading}
            style={{ 
              padding: "0 24px", backgroundColor: loading ? "#9ca3af" : "#3b82f6", color: "white", 
              border: "none", borderRadius: "8px", fontWeight: "600",
              cursor: loading ? "not-allowed" : "pointer", transition: "background-color 0.2s"
            }}
          >
            {loading ? "..." : "Send"}
          </button>
        </div>

        {/* DIVIDER */}
        <hr style={{ border: "none", borderTop: "1px solid #e5e7eb", margin: "10px 0" }} />

        {/* SETTINGS GROUP */}
        <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
          
          {/* Difficulty */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <span style={{ fontSize: "0.9rem", color: "#6b7280", fontWeight: "500" }}>Bot Level:</span>
            <div style={{ display: "flex", gap: "8px" }}>
              <button
                onClick={() => setDifficulty("Beginner")}
                style={{
                  backgroundColor: difficulty === "Beginner" ? "#ebf5ff" : "transparent",
                  color: difficulty === "Beginner" ? "#2563eb" : "#6b7280", 
                  border: difficulty === "Beginner" ? "1px solid #bfdbfe" : "1px solid #e5e7eb",
                  padding: "6px 12px", borderRadius: "6px", fontSize: "0.85rem", fontWeight: "600", cursor: "pointer"
                }}
              >
                Beginner
              </button>
              <button 
                onClick={() => setDifficulty("Intermediate")}
                style={{ 
                  backgroundColor: difficulty === "Intermediate" ? "#ebf5ff" : "transparent",
                  color: difficulty === "Intermediate" ? "#2563eb" : "#6b7280", 
                  border: difficulty === "Intermediate" ? "1px solid #bfdbfe" : "1px solid #e5e7eb",
                  padding: "6px 12px", borderRadius: "6px", fontSize: "0.85rem", fontWeight: "600", cursor: "pointer"
                }}
              >
                Intermediate
              </button>
            </div>
          </div>

          {/* Speed */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <span style={{ fontSize: "0.9rem", color: "#6b7280", fontWeight: "500" }}>Bot Speed:</span>
            <div style={{ display: "flex", gap: "8px" }}>
              {[
                { label: "Slow", val: 0.4 },
                { label: "Normal", val: 0.7 },
                { label: "Fast", val: 1 }
              ].map((speed) => (
                <button 
                  key={speed.val}
                  onClick={() => setAudioSpeed(speed.val)}
                  style={{ 
                    backgroundColor: audioSpeed === speed.val ? "#f3f4f6" : "transparent",
                    color: audioSpeed === speed.val ? "#111827" : "#6b7280",
                    border: audioSpeed === speed.val ? "1px solid #d1d5db" : "1px solid transparent",
                    padding: "6px 12px", borderRadius: "6px", fontSize: "0.85rem", fontWeight: "600", cursor: "pointer"
                  }}
                >
                  {speed.label}
                </button>
              ))}
            </div>
          </div>

        </div>

      </div>
    </main>)
};